Spring:
  application:
    name: Blog

  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: anyika
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/blogdb

server:
  port: 9090

# Jackson pretty print for readable JSON (optional)
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
